baseURL: http://example.org/
languageCode: en-us
title: Lucas N. Ferreira
theme: "PaperMod"

menu:
    main:
        - name: Home
          url: home
          weight: 5
        - name: Publications
          url: publications
          weight: 5
        - name: Research
          url: research
          weight: 5
        - name: Teaching
          url: teaching
          weight: 5
        - name: Resources
          url: resources
          weight: 5
        - name: Notes
          url: notes
          weight: 5

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light
    disableThemeToggle: true
    # disableThemeToggle: true
    # ShowShareButtons: true
    # ShowReadingTime: true
    # disableSpecial1stPost: true
    # displayFullLangName: true
    # ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    # ShowCodeCopyButtons: true
    # ShowRssButtonInSectionTermList: true
    # ShowToc: true
    # comments: false

    # homeInfoParams:
    #     Content: home

    socialIcons:
        - name: Github
          url: "https://github.com/adityatelange/hugo-PaperMod"
        - name: Google Scholar
          url: "https://ko-fi.com/adityatelange"
        - name: Twitter
          url: "https://discord.gg/ahpmTvhVmp"
        - name: Linkedin
          url: "index.xml"
